Check that we are working on main

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -8,6 +8,14 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: make sure we are on main
+      run: |
+        BRANCH="$(git branch --show-current)"
+        if [[ "$BRANCH" != "main"]]; then
+          echo 'Cannot publish subrepo on another branch than main';
+          exit 1;
+        fi
+        
     - name: create new git repo in subfolder and push
       run: |
         git init -b main
